---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: "~/chef-repo/data_bags/"
  encrypted_data_bag_secret_key_path: "~/chef-repo/secrets/chef/encrypted_data_bag_secret"

verifier:
  name: inspec

platforms:
  - name: centos7
    driver:
      box: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[jenkins_jnlp_test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      jenkins_slave:
        number_of_executors: 2
        usage: exclusive
        username: <%= ENV['JENKINS_MASTER_USERNAME'] %>
        labels:
          - test-kitchen
          - owner-<%= ENV['USER'] %>
        ssh_key_databag_item: <%= ENV['JENKINS_SSH_KEY_DATABAG_ITEM'] %>
      jenkins:
        master:
          endpoint: <%= ENV['JENKINS_MASTER'] %>
      java:
        jdk_version: '8'
        update_version: '112'
